KitapSatis/Models/Favorite.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KitapSatis.Models
{
    public class Favorite
    {
        [Key]
        public int Id { get; set; }
        public string UserId { get; set; }
        public List<FavoriteItem> FavoriteItems { get; set; }
    }
}

KitapSatis/Controllers/FavoriteController.cs
using KitapSatis.Abstract;
using KitapSatis.Data;
using KitapSatis.Identity;
using KitapSatis.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace KitapSatis.Controllers
{
    [Authorize(Roles = "Customer")]
    public class FavoriteController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<User> _userManager;
        private readonly IFavoriteService _favoriteService;
        public FavoriteController(ApplicationDbContext db, UserManager<User> userManager, IFavoriteService favoriteService)
        {
            _db = db;
            _userManager = userManager;
            _favoriteService = favoriteService;
        }
        public IActionResult Index()
        {
            var favorite = _favoriteService.GetFavoriteByUserId(_userManager.GetUserId(User));

            return View(new FavoriteModel()
            {
                FavoriteId = favorite.Id,
                FavoriteItems = favorite.FavoriteItems.Select(i => new FavoriteItemModel()
                {
                    FavoriteItemId = i.Id,
                    ProductId = i.ProductId,
                    Name = i.Product.ProductName,
                    Price = (double)i.Product.Price,
                    ImageUrl = i.Product.Picture,
                }).ToList()

            }) ;
        }
        [HttpPost]
        public IActionResult AddFavorite(int productId)
        {
            var userId = _userManager.GetUserId(User);
            _favoriteService.AddFavorite(userId,productId);
            return RedirectToAction("index");
        }
        [HttpPost]
        public IActionResult DeleteFromFavorite(int productId)
        {
            var userId = _userManager.GetUserId(User);
            _favoriteService.DeleteFromFavorite(userId, productId);
            return RedirectToAction("index");
        }

    }
}

KitapSatis/Views/Favorite/Index.cshtml
@model FavoriteModel

<br />


@if(Model.FavoriteItems.Count==0)
{
    <div class="row">
        <div class="col-12">
            <div class="alert alert-warning">
                Favorilerinizde ürün bulunmamaktadır.
            </div>
        </div>
    </div>
}
else{
<div class="row">
    <div class="col-md-12">
        <div class="text-left">
            <h4>Favorilerimdeki Ürünler</h4>
        </div>
            <table class="table table-hover">
            <thead>
                <tr>
                    <th></th>
                    <th>Ürün Adı</th>
                    <th>Fiyat</th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.FavoriteItems)
           {
               
             <tr>
                <td>
                    <a asp-controller="product"  asp-action="details" asp-route-Id="@item.ProductId">
                    <img src="~/img/productImages/@item.ImageUrl" width="100" alt="">
                    </a>
                </td>
                <td>@item.Name</td>
                <td>@item.Price ₺</td>
                <td>
                    @*<form method="post" asp-controller="Cart" asp-action="AddCart" style="display:inline> 
                    <input type="hidden" name="ProductId" value="@item.ProductId>
                     <input type="hidden" name="quantity" value="1">
                     <button type="submit" class="btn btn-primary btn-sm">Sepete Ekle</button>
                    </form>*@

                    <form asp-controller="Favorite" asp-action="DeleteFromFavorite" method="post">
                        <input type="hidden" name="productId" value="@item.ProductId">
                        <button type="submit" class="btn btn-danger btn-sm">
                            Kaldır
                        </button>
                    </form>
                </td>
            </tr>
            
           }
        </tbody>
    </table>
</div>
</div>
}